config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'foods#index'

    resources :foods 
    resources :exercises

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  validates :activity, presence: true
  validates :calories, presence: true

  def self.calorie_total
    sum = 0
    all.each do |exercise|
      sum += exercise.calories
    end
    return sum
  end

  def self.search(search)
    if search
      where('activity LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :calories, presence: true

  def self.calorie_total
    sum = 0
    all.each do |food|
      sum += food.calories
    end
    return sum
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :foods
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :find_exercise, except: [:new, :create, :index]
  before_action :authenticate_user!, except: [:show]

  def index
    @exercises = Exercise.all.order(created_at: :desc)
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to  foods_path
    else
      render :new
    end
  end

  def edit
    @exercise = Exercise.find(params[:id])
    render :edit
  end

  def update
    @exercise = Exercise.find(params[:id])

    if @exercise.update(exercise_params)
      redirect_to foods_path
    else
      render :edit
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    redirect_to foods_path
  end

  private
  
  def exercise_params
    params.require(:exercise).permit(:activity, :calories, :user_id)
  end

  def find_exercise
    @exercise = Exercise.find(params[:id])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, except: [:new, :create, :index]
  before_action :authenticate_user!, except: [:show]

  def index
    @foods = current_user.foods.all.search(params[:search])
    @exercises = current_user.exercises.all.search(params[:search])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to  foods_path
    else
      render :new
    end
  end

  def edit
    @food = Food.find(params[:id])
    render :edit
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to foods_path
    else
      render :edit
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private
  
  def food_params
    params.require(:food).permit(:name, :calories, :user_id)
  end

  def find_food
    @food = Food.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/_exercises_list.html.erb
<table border="1" style="width:25%">
  <caption>Exercise</caption>
  <tr>
    <th><center>Activity</center></th>
    <th><center>Calories</center></th>
  </tr>

  <% exercises.each do |exercise| %>
    <tr>
      <td>
        <center>
          <%= exercise.activity %>
          <%= link_to 'Edit', edit_exercise_path(exercise) %>
          <%= link_to "Delete", exercise_path(exercise),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </center>
      </td>
      <td>
        <center>
          <%= exercise.calories %>
        </center>
      </td>
    </tr>
  <% end %>
</table>

app/views/exercises/_form.html.erb
<div class='form-group'>
  <%= form_for @exercise, html: { multipart: true } do |f| %>
    <%= f.label :activity %>
    <%= f.text_field :activity, class: "form-control", required: 'required' %>
    <%= f.label :calories %>
    <%= f.text_field :calories, class: "form-control", required: 'required' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/exercises/edit.html.erb
<%= render 'form' %>

app/views/food/_form.html.erb
<%= form_for @food, html: { multipart: true } do |f| %>
<%= f.error_messages %>

<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: 'required' %>
  <%= f.label :calories %>
  <%= f.text_field :calories, class: "form-control", required: 'required' %>
  <%= f.hidden_field :user_id, value: current_user.id %>

</div>

<div class='form-group'>
  <%= f.submit class: 'btn btn-success' %>
</div>
<% end %>

app/views/foods/_foods_list.html.erb
<table border="1" style="width:25%">
  <caption>Food</caption>
  <tr>
    <th><center>Name</center></th>
    <th><center>Calories</center></th>
  </tr>
  <% foods.each do |food| %>
    <tr>
      <td>
        <center>
          <%= food.name %>
          <%= link_to 'Edit', edit_food_path(food) %>
          <%= link_to "Delete", food_path(food),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </center>
      </td>
      <td>
        <center>
          <%= food.calories %>
        </center>
      </td>
    </tr>
  <% end %>
</table>

app/views/foods/_form.html.erb
<div class='form-group'>
  <%= form_for @food, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: 'required' %>
    <%= f.label :calories %>
    <%= f.text_field :calories, class: "form-control", required: 'required' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit class: 'btn btn-success' %>
  <% end %>
</div>

app/views/foods/edit.html.erb
<%= render 'form' %>

app/views/foods/index.html.erb
<div>
  <%= form_tag foods_path, :method => 'get', :id => "search", remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <% end %>
  <div id="food-list">
    <%= render 'foods_list', foods: @foods %>
  </div>
  <br>
  <%= form_for (Food.new) do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: 'required' %>
    <%= f.label :calories %>
    <%= f.text_field :calories, class: "form-control", required: 'required' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-success' %>
  </div>
  <% end %>
  <p>
    <b>Calories Consumed:</b> <%= @foods.calorie_total %>
  </p>
  <div id="exercises-list">
    <%= render 'exercises/exercises_list', exercises: @exercises %>
  </div>
  <br>
  <%= form_for (Exercise.new) do |f| %>
  <div class='form-group'>
    <%= f.label :activity %>
    <%= f.text_field :activity, class: "form-control", required: 'required' %>
    <%= f.label :calories %>
    <%= f.text_field :calories, class: "form-control", required: 'required' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-success' %>
  </div>
  <% end %>
  <p>
    <b>Calories Burned:</b> <%= @exercises.calorie_total %>
  </p>
  <h2>Daily Calorie Balance: <%= @foods.calorie_total - @exercises.calorie_total %></h2>
</div>

app/views/foods/index.js.erb
$('#food-list').html('<%= j render 'foods_list', foods: @foods %>')
$('#exercises-list').html('<%= j render 'exercises/exercises_list', exercises: @exercises %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calorie Cruncher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <b><%= link_to "Calorie Cruncher", foods_path, id:'flickr', class: "navbar-brand" %></b>
      </div>
      <ul class="nav navbar-nav navbar-right">

    <p>
      <% unless current_user %>
      <%= link_to 'Sign in', new_user_session_path, id:'text-color', class: "navbar-brand"  %>
      <%= link_to 'Sign up', new_user_registration_path, id:'text-color', class: "navbar-brand"  %>
      <% else %>
      <%= link_to current_user.email, edit_user_registration_path, id:'text-color', class: "navbar-brand"  %>
      <%= link_to 'Log out',  destroy_user_session_path, method: 'delete', id:'text-color', class: "navbar-brand"  %>
      <% end %>
  </p>
    </ul>

</div>
</nav>

<div class='container'>
  <% if alert %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

  <% if notice %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
  <br>

  <%= yield %>
</div>

</body>
</html>